repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.5
    hooks:
      - id: terraform_fmt
      - id: terraform_trivy
        args:
          - --args=--severity=HIGH
      - id: terraform_tflint
        args:
          - --args=--minimum-failure-severity=error